/*
 * @Description: the global variables for the scripts
 * @Version: 1.0.0.20220205
 * @Author: Arvin Zhao
 * @Date: 2021-12-13 19:19:29
 * @Last Editors: Arvin Zhao
 * @LastEditTime: 2022-02-05 12:04:02
 */

global.common = {
  ANIMATION_DURATION: 300,
  API_ACCESS_DENIED_PAGE_TITLE: "拒绝访问",
  APP_SCHEME: "app",
  APP_WIN_ID: "kobe-app",
  APPEARANCE_KEY: "appearance",
  BAIDU_ID: "baidu",
  BUTTON_GROUP: "buttonGroup",
  CORRECT_WIN_COLOUR: "correctWinColour",
  DARK_MODE_ID: "dark",
  DARK_WIN_COLOUR: "#000",
  DATE_PICKER: "datePicker",
  DATE_RANGE_PICKER_NAME: "dateRangePickerDateRange",
  DATE_RANGE_PICKER_TOOLTIP_NAME: "tooltipDateRange",
  DAY_TIME_START: " 00:00:00",
  DEFAULT_MAX_DATE_RANGE_SPAN: 4,
  DEV: "development",
  END_DATE_KEY: "endDate",
  EXTERNAL_SEARCH_KEY: "externalSearch",
  FAST_MODE_ID: "fast",
  FILE_HEADER_FONT_SIZE: 14,
  GET_APP_NAME: "getAppName",
  GET_APPEARANCE: "getAppearance",
  GET_CONTENT_SIZE: "getContentSize",
  GET_EXTERNAL_SEARCH: "getExternalSearch",
  GET_MAX_DATE_RANGE_SPAN: "getMaxDateRangeSpan",
  GET_MIN_DATE: "getMinDate",
  GET_SEARCH_ENGINE_MODE: "getSearchEngineMode",
  GET_SEARCH_RESULT_DATA: "getSearchResultData",
  GET_STOCK_LIST: "getStockList",
  GOOGLE_ID: "google",
  HOME_VIEW: "home",
  IPC_RECEIVE: "fromMain",
  IPC_RENDERER_API_KEY: "ipcRenderer",
  IPC_SEND: "toMain",
  LIGHT_MODE_ID: "light",
  LIGHT_WIN_COLOUR: "#FFF",
  MACOS: "darwin",
  MAX_DATE_RANGE_SPAN_KEY: "maxDateRangeSpan",
  MIN_COLUMN_WIDTH: 50,
  MIN_DATE_KEY: "minDate",
  MIN_DATE_PICKER_TOOLTIP_NAME: "tooltipMinDate",
  MIN_MIN_DATE: "1990-12-03",
  PREFERENCE_WIN_ID: "kobe-preferences",
  PREFERENCE_VIEW: "preferences",
  PROCESSOR_ERROR_KEY: "ProcessorError",
  SEARCH_BAR_ID: "search-bar",
  SEARCH_ENGINE_MODE_KEY: "searchEngineMode",
  SEARCH_FORM_ID: "search-form",
  SEARCH_RESULT_AREA_ID: "search-result-area",
  SEARCH_RESULT_GRID_NAME: "gridSearchResults",
  SEARCH_RESULT_VIEW: "searchResults",
  SEARCH_STATUS_AREA_ID: "search-status-area",
  SEPARATOR: "separator",
  SET_APPEARANCE: "setAppearance",
  SET_EXTERNAL_SEARCH: "setExternalSearch",
  SET_MAX_DATE_RANGE_SPAN: "setMaxDateRangeSpan",
  SET_MIN_DATE: "setMinDate",
  SET_SEARCH_ENGINE_MODE: "setSearchEngineMode",
  SF_ALIGN_CENTRE: "Center",
  SF_ALIGN_LEFT: "Left",
  SF_ALIGN_RIGHT: "Right",
  SF_AUTO_COMPLETE_INPUT_CLASSES: "e-autocomplete e-input",
  SF_AUTO_COMPLETE_POP_UP_CLASSES: "e-ddl e-popup e-popup-open",
  SF_BEFORE: "Before",
  SF_BOTH: "Both",
  SF_CULTURE: "zh-Hans",
  SF_DATE_RANGE_PICKER_POP_UP_CLASSES: "e-daterangepicker e-popup e-popup-open",
  SF_EASE: "ease",
  SF_ELLIPSIS_WITH_TOOLTIP: "EllipsisWithTooltip",
  SF_EQUAL: "equal",
  SF_ERROR_CLASS: "e-error",
  SF_FADE_IN: "FadeIn",
  SF_MENU: "Menu",
  SF_MOVABLE_CONTENT_CLASS: "e-movablecontent",
  SF_MULTIPLE: "Multiple",
  SF_NARROW: "Narrow",
  SF_NUM: "number",
  SF_STYLES: "syncfusionStyles",
  SF_TAILWIND: "tailwind",
  SF_TAILWIND_DARK: "tailwind-dark",
  SLIDER: "slider",
  SMOOTH_SCROLL: "smooth",
  STABLE_MODE_ID: "stable",
  START_DATE_KEY: "startDate",
  STOCK_NAME_KEY: "name",
  STOCK_SYMBOL_AUTO_COMPLETE_NAME: "autoCompleteStockSymbol",
  STOCK_SYMBOL_KEY: "ts_code",
  STOCK_SYMBOL_TOOLTIP_NAME: "tooltipStockSymbol",
  STRIKE_PRICE_KEY: "strikePrice",
  SYSTEM_DEFAULT_MODE_ID: "system",
  TAG_KEY: "tag",
  TOTAL_VOLUME_KEY: "totalVolume",
  TRICK_INPUT_ID: "trick-input",
  UNKNOWN: "Unknown",
  WIN_HEIGHT_MIN: 600,
  WIN_WIDTH_MIN: 800,
  WINDOWS: "win32",
};

export default global;
