version: 2.1
jobs:
  build_macos:
    macos:
      xcode: "13.3.0"
    steps:
      - checkout
      - run: npm install
      - run: npm run electron:build -- -m

  build_windows:
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - run: npm install
      - run: npm run electron:build -- -w --arm64 --x64 --ia32

workflows:
  version: 2
  build_kobe:
    jobs:
      - build_macos
      - build_windows