# Reference: https://circleci.com/blog/electron-builds/
version: 2.1
jobs:
  build_macos:
    macos:
      xcode: 13.3.0
    steps:
      - checkout
      - run:
          command: sudo npm install -g npm
          name: Update npm
      - restore_cache:
          key: kobe-macos-{{ checksum "package.json" }}
      - run: 
          command: npm install
          name: Install dependencies
      - save_cache:
          key: kobe-macos-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: 
          command: npm run electron:build -- -m
          name: Generate builds
      - store_artifacts:
          path: ~/kobe/artifacts
    working_directory: ~/kobe

  build_windows:
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - run:
          command: sudo npm install -g npm
          name: Update npm
      - restore_cache:
          key: kobe-windows-{{ checksum "package.json" }}
      - run: 
          command: npm install
          name: Install dependencies
      - save_cache:
          key: kobe-windows-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          command: npm run electron:build -- -w --arm64 --x64 --ia32
          name: Generate builds
      - store_artifacts:
          path: ~/kobe/artifacts
    working_directory: ~/kobe

workflows:
  version: 2
  build_kobe:
    jobs:
      - build_macos
      - build_windows